### ISSUE TITLE
8) Feature: Organization can see projects of implementing partners

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#124]
As user of an organization to see reports, projects of implementing partners on admin page

**Comment by pfitzpaddy** [comment]
This will be a nice feature and has been a common request.

**Tasks**
- [x] Add Implementing Partner in Project Details from a multiple select referencing the Organizations list
- [x] Filter Admin dashboard to display user access defaults + Implementing Partner reports

**Comment by drfaustusfade** [comment]
- [ ] add Donees filter for organization donees, like usaid

**Comment by drfaustusfade** [comment]
ref: https://github.com/pfitzpaddy/ngm-reportDesk/issues/205

**Comment by drfaustusfade** [comment]
implemented in https://github.com/pfitzpaddy/ngm-reportEngine/pull/103, can be closed

**Comment by pfitzpaddy** [comment]
Merged
