### ISSUE TITLE
1) Epic: One ORG Per Country

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#127]
Currently a ORG is created for each cluster in each country. As such its possible to have 2 ORGs (one for Health, one for WaSH) for Afghanistan, This should be 1 ORG for Afghanistan with as many clusters as required.

**Tasks**
- [x] Remove filter for cluster when creating an organization [here in User model](https://github.com/pfitzpaddy/ngm-reportEngine/blob/master/api/models/ReportHub/User.js#L213)
- [x] Add left menu to filter on clusters on ORG Projects page
- [x] Add cluster_id param on project page based on menu selection
- [x] Add cluster tag in projects HTML list (ToDo, Complete)
- [x] ~~Remove filter for cluster when creating stocks [here in StockWarehouse model](https://github.com/pfitzpaddy/ngm-reportEngine/blob/master/api/models/Cluster/Stocks/StockWarehouse.js#L165)~~ The `StockWarehouse` uses `organization_id`, not `admin0pcode, cluster_id, organization`
- [x] Update all HTML Project / Stock Templates to remove cluster from title and replace description in sub-title with project ID and list of clusters in sub-title
![rh-title-update](https://user-images.githubusercontent.com/1784705/49863252-82fe2300-fe1d-11e8-9a53-8713e4ef49a2.png)

**db Updates**
- [x] Database updates to convert cluster_id, cluster to arrays (projects, reports)
- [x] Database updates to normalise ORGs (merge multiple country ORG records / IDs into one ORG)
- [x] Database updates to USERS to update to normalized ORGs
- [x] Database updates to convert cluster_id, cluster to arrays (stocks)
- [x] Database updates to normalise stocks

**Comment by drfaustusfade** [comment]
**Update to db Updates:**
Currently, organization collection contains obsolete multiple organizations for each cluster

For AF
Clean up:
- [x] Clean up loose duplicates on organization collections
- [x] Clean up loose duplicates on user collection
- [x] Clean up organization tags and organization ids due to various glitches 

Update plan: 
- [x] Clean up as per above
- [x] Update organization in all collections by assigning to first registered its organization if multiple cluster-country
- [x] Update first organization if acbar partner in one of cluster-country organizations
- [x] Remove cluster properties from organizations and delete duplicates leaving first registered org

Notes: Warehouses have association ObjectId('organization_id);
		Multi-cluster old stocks reports (20 orgs in af ) to leave as it is, so that there will be n same reports( to put cluster tag on ui for the), after the organization update only one each reporting month, but could be updated to have only one report by pointing locations to one report


``` 
// example update script for regular collections
db.getCollection("beneficiaries").find({ admin0pcode: "AF" }).forEach(function (d) {
    if (d.organization_tag) {
        var t = db.getSiblingDB('ngmReportHub').getCollection("organization").findOne({ organization_tag: d.organization_tag, admin0pcode: "AF" })
        if (t) {
            d.organization_id = t._id.valueOf();
            db.getCollection("beneficiaries").save(d);
        } else {
            print('miss-L1', d.organization_id, d.organization_tag, d._id.valueOf())
        }
    } else {
        print('miss-L2', d.organization_id, d.organization_tag, d._id.valueOf())
    }
});
// stockwarehouse have objectid
db.getCollection("stockwarehouse").find({ admin0pcode: "AF", organization_id: {$ne: null} }).forEach(function (d) {
    if (d.organization_tag) {
        var t = db.getSiblingDB('ngmReportHub').getCollection("organization").findOne({ organization_tag: d.organization_tag, admin0pcode: "AF" })
        if (t) {
            d.organization_id = t._id;
            db.getCollection("stockwarehouse").save(d);
        } else {
            print('miss-L1', d.organization_id, d.organization_tag, d._id.valueOf())
        }
    } else {
        print('miss-L2', d.organization_id, d.organization_tag, d._id.valueOf())
    }
});
```

TODO: put cluster tag on ui for historical report records and warehouses

**Comment by drfaustusfade** [comment]
AF records were updated to Organization per Country, no issues so far found
