### ISSUE TITLE
4) Feature: Notifications Update

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#129]
**Tasks**
- [x] The first user to register a new country [ admin0pcode, Organization ] becomes ORG ADMIN
- [x] On registration of a new user, notification should be sent to ORG ADMINs.
- [x] Monthly Reminders sent to PROJECT FOCAL POINT only
