### ISSUE TITLE
5) Epic: Admin Lists UI

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#131]
Currently, the only way to update activity lists is via a database update.

Cluster ADMINs should have access to update their cluster activities to match the requirements of their response via the UI. A default set should be made available for new countries.

**Tasks**
- [ ] Create an Admin page at '/cluster/admin/lists' that provides access to lists [ Organizations, Donors, Activities, Stocks, Beneficiaries, Units ] as cards
<img width="1017" alt="screen shot 2018-12-12 at 9 43 55 pm" src="https://user-images.githubusercontent.com/1784705/49888018-8912f480-fe5b-11e8-873b-a124152d2921.png">

**Organizations**
- Organizations can be searchable from a global RH list and made active / not-active for a country response.
- Organisations can be added to the master RH list (if missing) via searching from HDX or being manually added

**Donors**
- Donors can be searchable from a global RH list and made active / not-active for a country response.
- Donors can be added to the master RH list (if missing) via searching from HDX or being manually added

**Activities**
- [ ] For Activities, lists should be grouped into response plans or years and can be active / not-active. Only one group / list at a time can be active
- [ ] A new list will automatically become active (and make the old list not-active).
- [ ] Updating an active list will update relevant data throughout the database
- [ ] Update an old list will update relevant historical data throughout the database
- [ ] Activities can be 2-tier or 3-tier

**Stocks**
- [ ] Stocks can be searchable from a global RH list and made active / not-active for a country response.

**Beneficiaries**
- [ ] For Beneficiaries, lists should be grouped into response plans or years and can be made active / not-active. Only one group / list at a time can be active.

**Units**
- [ ] Units can be searchable from a global RH list and made active / not-active for a country response.

**Access**
- Country Admins should be able to edit [ Organisations, Donors, Beneficiaries ] only
- Cluster Admins should be able to edit [ Organizations, Donors, Activities, Stocks, Beneficiaries, Units ]

**Comment by drfaustusfade** [comment]
![img_activities_mng](https://user-images.githubusercontent.com/29349472/50135958-c17b5e00-02b3-11e9-8140-e143f41e2c8f.jpg)
UI/UX activities management sketch

**Comment by pfitzpaddy** [comment]
For this, I currently have "active" in activities.csv but thats not correct. What we could do is
- have a start_date, end_date, activity_tag (unique to date range) of each activity and then filter activities based on project_start_date, project_end_date at the initial time of project creation, and;
- assign the tag to the project based on the list used at the time of creation, for future manipulation (to query by tag, not date range, which might be extended).

**Comment by pfitzpaddy** [comment]
Bumping this issue, I think we should make a first start on this for the more basic lists, eventually tackling the more difficult issue of activities.

1. To begin, there should be an Admin landing page @ #/cluster/admin
**Note**: the **Access** conditions are specified above in the first comment of this issue
![sketch](https://user-images.githubusercontent.com/1784705/70407066-19831580-1a6d-11ea-9071-69ef54f7c879.jpg)
2. The landing page will include [ Cluster (links to the default landing page @ #/cluster/organization), Dashboards (@ #/cluster/admin/etc), Lists (@ #/cluster/admin/lists)  ]. 
**Note**, there might be a route conflict on #/cluster/admin, something to keep in mind.
3. This Admin page should also be available from the left menu (My Admin), along with the sub links.
4. The admin lists would then be available @ #/cluster/admin/lists (as described in the **Tasks** above)

The first lists to tackle could be organizations, donors and beneficiary types.
**Side Note** An Organization might also be a of type donor, programme partners, implementing partner, but no need to worry about that now.

I suggest starting to integrate the code as soon as possible, making the pages visible only to our accounts (i.e. user.email === 'pfitzgerald' && user.email === 'tkilkeiev' && user.email === 'farifin', etc, or whatever accounts us 3 are using). This way we can have the code integrated and reviewed and rolled out with so many other changes ongoing easily.

**Comment by pfitzpaddy** [comment]
I recommend @fakhrihawari to take a look at this, unless you have other pressing issues. Any questions or clarifications contact Skype group Alpha at any time.

**Comment by drfaustusfade** [comment]
next on the list to tackle, after there is rtl support almost implemented, the good thing @fakhrihawari worked on it and did many things, the plan is to start with beneficiary types
I support the idea of the practice of committing early and often

**Comment by fakhrihawari** [comment]
@pfitzpaddy  and @drfaustusfade  so what should we call this admin "master"?

**Comment by fakhrihawari** [comment]
Init :
https://github.com/fakhrihawari/ngm-reportHub/tree/admin-list-2.0

**Comment by pfitzpaddy** [comment]
Adding another page we might want to add during this admin development -> **APIs**.
The API card would load a page with lists of APIs and the params. This would be useful for the IMOs to access data. This is low priority and not urgent. With APIs, we should also look into adding a key param for security or including something for authentication - whatever we choose it would have to also work with Power Bi

**Comment by fakhrihawari** [comment]
Are beneficiary types and beneficiaries the same things?
Cause in the task above just mention the detailed task about beneficiaries, not detailed task about the beneficiary type

**Comment by drfaustusfade** [comment]
In the task it’s the same, beneficiary type in RH is population group to provide services, meaning people, beneficiaries are also people served in general, hence the confusion, also it can be viewed as subclass of beneficiaries

**Comment by pfitzpaddy** [comment]
**APIs Page** -> Could be a page that also generates API key for user.

**Comment by drfaustusfade** [comment]
PROPOSAL/DISCUSSION for admin lists structure
----
The **main idea** is to organize all lists by **Response Plan**

Page for country admin/cluster admin would include:
Global lists for view, Country lists (Organizations, Admins, ...), Plans

Plans -> List of Plans -> Plan Def & List of Clusters -> Plan Cluster lists ( Cluster...Beneficiary types, Activities, Donors, Site Types, Site Implementations, Indicators, Units, etc )

Each list would be referenced by PlanID, dates, tag etc
A list would follow usual card form like interface, for country cluster list it would be possible to select values from global or maybe also functionality to add custom values
The functionality of all components could be adjusted per Response Plan, for example, 5w would contain for Response Plans filter etc
PlanID, PlanTag, could be added to beneficiary data, for reference and updates
Further development could include Copy Plan, Plan Templates etc
The first version could contain just one continuous ongoing plan for simplicity

![imageedit_1_5111097684](https://user-images.githubusercontent.com/29349472/72892771-03879680-3d35-11ea-8fec-6c3ebde0c7a2.jpg)
