### ISSUE TITLE
3) Feature: Cluster_id to Array based on New Project Activities

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#133]
When adding a New Project, the project is assigned to the USERs cluster (there is no way to change this)

A projects cluster should be based on the project Activities selection (no need for a modal!). The list of default Activities will be based on the USERs cluster (i.e. Health, WaSH)

This will make the cluster_id and cluster tags arrays, but will also provide more visibility as the project will appear on all cluster Admin pages.

**Tasks**
- [ ] Update cluster_id and cluster to array in all existing models
- [ ] db update to cluster_id and cluster to array in all existing tables / collections
- [ ] Update Project cluster_id and cluster based on user selection of Activities during Add New Project

**Comment by drfaustusfade** [comment]
there is already a compilation of values for example like activity_type or inter_cluster_activities that contain cluster, to be even more clear, we can have an additional field, clusters: [ {
            "cluster_id" : "wash", 
            "cluster" : "WASH", 
        } ... with the same kind of processing, and additionally use it to update title of project, to be complete multicluster like
