### ISSUE TITLE
Project Plan: Project Partners project/locations multiple selections

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#205]
OCHA requested to add per location implementing partners editing to improve implementing partners monitoring per locations
Solution: 
- [x] standardize multiple selections, removing text-based input -- using chips
- [x] add functionality to edit locations implementing partners:
  - only selected values from defined in details, checked all by default, unchecking if not needed
  - on a new partner edit addition in details, the partner will be added for all location checked
  - update implementing_partners compilation
- [ ] check historical data implementing partners

**Comment by drfaustusfade** [comment]
related https://github.com/pfitzpaddy/ngm-reportDesk/issues/186

**Comment by pfitzpaddy** [comment]
Not sure about this.... will need to learn more. OCHAs ideas so far have not been very good. Implementing Partners per location is something that can be deduced from the Beneficiaries download. Im not sure I understand what they are asking for, but if they tell us WHAT they need we can come up with a solution, they should not tell us the HOW (i.e. look at the Strategic Objectives / Indicators soltion for AFG). We will need to brainstorm before we start this work.

**Comment by drfaustusfade** [comment]
the problem is: if defining [Partner1, Partner2] in Project for locations [Location1, Location2] and if Partner1 is in Location1 and not in Location2 that needs to be tracked, to have a clearer picture of who is where

**Comment by pfitzpaddy** [comment]
Yes if it can be linked to that bigger issue of Implementing Partners https://github.com/pfitzpaddy/ngm-reportDesk/issues/186 then we can trial it for Afghanistan. It could also lead into reporting on "joint" projects. i.e. Implementing Partner reports for Location 1 of UNHCR project. Its quite a big ask, but would be something really good. i.e. When UNHCR makes a project they can "invite" the Implementing Partner to access the project who then receive an email notification and have access to report on the specific locations allocated to them by UNHCR.

**Comment by pfitzpaddy** [comment]
Just a note for OCHA tho, the 4Ws in principal already achieves this they are just being lazy. Since the partners would benefit (those with Implementing Partners etc) its a good idea.

**Comment by drfaustusfade** [comment]
as implementing partners to be array, it is possible to filter reports/projects for admin dashboard, showing reports/projects where organization is implementing partner; commonly requested feature

**Comment by fakhrihawari** [comment]
Link pull request:
https://github.com/pfitzpaddy/ngm-reportHub/pull/180
