### ISSUE TITLE
Make ReportHub modals sexy again....

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#314]
Modal are looking tired and lame.
![ReportHub_modals](https://user-images.githubusercontent.com/1784705/74233864-bf653180-4cf5-11ea-8325-f8b3fc51d5b3.png)

**Tasks**
- [x] Update the buttons to be confirm on left, cancel on right
- [x] Update the confirm button to be normal button, cancel button to be flat button
- [x] Make the modals to be sexy again, samples below but @fakhrihawari go for something you think looks good

Modal 1
![form_1](https://user-images.githubusercontent.com/1784705/74234155-6ba71800-4cf6-11ea-82d5-6af899cfd00c.png)
Modal 2
![form_2](https://user-images.githubusercontent.com/1784705/74234162-6f3a9f00-4cf6-11ea-9e58-754dc1dacf7b.jpeg)
Modal 3
![form_3](https://user-images.githubusercontent.com/1784705/74234174-72ce2600-4cf6-11ea-9225-f78725bf3cb9.png)

**Comment by fakhrihawari** [comment]
<img width="1035" alt="Screen Shot 2020-02-12 at 11 12 47" src="https://user-images.githubusercontent.com/12655589/74302304-a5c0fa00-4d88-11ea-96b3-7ed704a2bfc3.png">

Like this?

**Comment by pfitzpaddy** [comment]
Perfect

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/pfitzpaddy/ngm-reportHub/pull/344

**Comment by pfitzpaddy** [comment]
Merged
