### ISSUE TITLE
Pending todo Tasks as of 211118

### ISSUE THREAD

**Issue by drfaustusfade** [pfitzpaddy/ngm-reportDesk#70]
**Pending Tasks TODO** by priority 
- [x] AF Nutrition weekly reporting https://github.com/pfitzpaddy/ngm-reportDesk/issues/69
- [x] Copy last month monthly report https://github.com/pfitzpaddy/ngm-reportDesk/issues/41
- [x] User Management (Team Functionality) https://github.com/pfitzpaddy/ngm-reportDesk/issues/37
- [x] Stocks targeted groups https://github.com/pfitzpaddy/ngm-reportDesk/issues/56
- [x] Project progress stats https://github.com/pfitzpaddy/ngm-reportDesk/issues/58
- [ ] Hrp health stats https://github.com/pfitzpaddy/ngm-reportDesk/issues/46
- [x] Multi cluster Projects Admin View https://github.com/pfitzpaddy/ngm-reportDesk/issues/59
- [ ] Organization cluster projects view
