### ISSUE TITLE
Ethiopia - Protection Updates

### ISSUE THREAD

**Issue by pfitzpaddy** [pfitzpaddy/ngm-reportDesk#73]
### ToDo
- [ ] Add Returnee IDPs
- [ ] Make autocode disabled
- [ ] Add location MPT

**Comment by pfitzpaddy** [comment]
Updated on DEV and PROD https://github.com/pfitzpaddy/ngm-reportHub/commit/410ce00229ffa571775afc2a128d9c2cdfcc2ef5
